2019-05-14 17:31:25.280  INFO 88999 --- [main] c.gsafety.datasync.DataSyncApplication   : Starting DataSyncApplication v0.1 on bogon with PID 88999 (/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar started by huangll in /Users/huangll/workspace/data-sync/target)
2019-05-14 17:31:25.287  INFO 88999 --- [main] c.gsafety.datasync.DataSyncApplication   : No active profile set, falling back to default profiles: default
2019-05-14 17:31:27.980  INFO 88999 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$4d392b10] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-05-14 17:31:29.883  INFO 88999 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9090 (http)
2019-05-14 17:31:29.957  INFO 88999 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-05-14 17:31:29.959  INFO 88999 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.17]
2019-05-14 17:31:30.192  INFO 88999 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-05-14 17:31:30.192  INFO 88999 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 4780 ms
2019-05-14 17:31:31.165  INFO 88999 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2019-05-14 17:31:31.415  INFO 88999 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-05-14 17:31:31.975  INFO 88999 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2019-05-14 17:31:32.039  INFO 88999 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2019-05-14 17:31:32.122  INFO 88999 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2019-05-14 17:31:32.423  INFO 88999 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9090 (http) with context path ''
2019-05-14 17:31:32.433  INFO 88999 --- [main] c.gsafety.datasync.DataSyncApplication   : Started DataSyncApplication in 7.916 seconds (JVM running for 8.541)
2019-05-14 17:31:32.520  INFO 88999 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-14 17:31:32.533 ERROR 88999 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at DataSyncApplication.main(DataSyncApplication.java:10) [classes!/:0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [data-sync-0.1.jar:0.1]
Caused by: java.io.FileNotFoundException: class path resource [data-sync.yaml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar!/BOOT-INF/classes!/data-sync.yaml
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:180) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at DataPullManager.loadDataSyncConfig(DataPullManager.java:50) ~[classes!/:0.1]
	at DataPullManager.run(DataPullManager.java:44) ~[classes!/:0.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	... 13 common frames omitted

2019-05-14 17:31:32.549  INFO 88999 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-05-14 17:32:09.374  INFO 89088 --- [main] c.gsafety.datasync.DataSyncApplication   : Starting DataSyncApplication v0.1 on bogon with PID 89088 (/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar started by huangll in /Users/huangll/workspace/data-sync/target)
2019-05-14 17:32:09.379  INFO 89088 --- [main] c.gsafety.datasync.DataSyncApplication   : No active profile set, falling back to default profiles: default
2019-05-14 17:32:11.520  INFO 89088 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$3586a290] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-05-14 17:32:12.127  INFO 89088 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9090 (http)
2019-05-14 17:32:12.180  INFO 89088 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-05-14 17:32:12.181  INFO 89088 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.17]
2019-05-14 17:32:12.337  INFO 89088 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-05-14 17:32:12.337  INFO 89088 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2854 ms
2019-05-14 17:32:13.342  INFO 89088 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2019-05-14 17:32:13.591  INFO 89088 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-05-14 17:32:14.427  INFO 89088 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2019-05-14 17:32:14.479  INFO 89088 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2019-05-14 17:32:14.591  INFO 89088 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2019-05-14 17:32:15.076  INFO 89088 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9090 (http) with context path ''
2019-05-14 17:32:15.085  INFO 89088 --- [main] c.gsafety.datasync.DataSyncApplication   : Started DataSyncApplication in 6.503 seconds (JVM running for 7.278)
2019-05-14 17:32:15.175  INFO 89088 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-14 17:32:15.185 ERROR 89088 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at DataSyncApplication.main(DataSyncApplication.java:10) [classes!/:0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [data-sync-0.1.jar:0.1]
Caused by: java.io.FileNotFoundException: class path resource [data-sync.yaml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar!/BOOT-INF/classes!/data-sync.yaml
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:180) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at DataPullManager.loadDataSyncConfig(DataPullManager.java:50) ~[classes!/:0.1]
	at DataPullManager.run(DataPullManager.java:44) ~[classes!/:0.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	... 13 common frames omitted

2019-05-14 17:32:15.192  INFO 89088 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-05-14 17:35:53.903  INFO 89443 --- [main] c.gsafety.datasync.DataSyncApplication   : Starting DataSyncApplication v0.1 on bogon with PID 89443 (/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar started by huangll in /Users/huangll/workspace/data-sync/target)
2019-05-14 17:35:53.915  INFO 89443 --- [main] c.gsafety.datasync.DataSyncApplication   : No active profile set, falling back to default profiles: default
2019-05-14 17:35:56.575  INFO 89443 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$ab41717b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-05-14 17:35:57.398  INFO 89443 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9090 (http)
2019-05-14 17:35:57.465  INFO 89443 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-05-14 17:35:57.465  INFO 89443 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.17]
2019-05-14 17:35:57.682  INFO 89443 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-05-14 17:35:57.683  INFO 89443 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3679 ms
2019-05-14 17:35:58.696  INFO 89443 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2019-05-14 17:35:58.927  INFO 89443 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-05-14 17:35:59.618  INFO 89443 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2019-05-14 17:35:59.662  INFO 89443 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2019-05-14 17:35:59.741  INFO 89443 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2019-05-14 17:36:00.241  INFO 89443 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9090 (http) with context path ''
2019-05-14 17:36:00.248  INFO 89443 --- [main] c.gsafety.datasync.DataSyncApplication   : Started DataSyncApplication in 7.232 seconds (JVM running for 8.082)
2019-05-14 17:36:00.326  INFO 89443 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-14 17:36:00.334 ERROR 89443 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at DataSyncApplication.main(DataSyncApplication.java:10) [classes!/:0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [data-sync-0.1.jar:0.1]
Caused by: java.io.FileNotFoundException: class path resource [data-sync.yaml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar!/BOOT-INF/classes!/data-sync.yaml
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:180) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at DataPullManager.loadDataSyncConfig(DataPullManager.java:50) ~[classes!/:0.1]
	at DataPullManager.run(DataPullManager.java:44) ~[classes!/:0.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	... 13 common frames omitted

2019-05-14 17:36:00.341  INFO 89443 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-05-14 17:36:36.650  INFO 89521 --- [main] c.gsafety.datasync.DataSyncApplication   : Starting DataSyncApplication v0.1 on bogon with PID 89521 (/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar started by huangll in /Users/huangll/workspace/data-sync/target)
2019-05-14 17:36:36.660  INFO 89521 --- [main] c.gsafety.datasync.DataSyncApplication   : No active profile set, falling back to default profiles: default
2019-05-14 17:36:39.764  INFO 89521 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$fa19f0ab] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-05-14 17:36:40.417  INFO 89521 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9090 (http)
2019-05-14 17:36:40.481  INFO 89521 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-05-14 17:36:40.482  INFO 89521 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.17]
2019-05-14 17:36:40.686  INFO 89521 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-05-14 17:36:40.686  INFO 89521 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3894 ms
2019-05-14 17:36:41.756  INFO 89521 --- [main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2019-05-14 17:36:42.007  INFO 89521 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-05-14 17:36:42.685  INFO 89521 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2019-05-14 17:36:42.748  INFO 89521 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2019-05-14 17:36:42.838  INFO 89521 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2019-05-14 17:36:43.162  INFO 89521 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9090 (http) with context path ''
2019-05-14 17:36:43.170  INFO 89521 --- [main] c.gsafety.datasync.DataSyncApplication   : Started DataSyncApplication in 7.335 seconds (JVM running for 8.031)
2019-05-14 17:36:43.273  INFO 89521 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-05-14 17:36:43.286 ERROR 89521 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at DataSyncApplication.main(DataSyncApplication.java:10) [classes!/:0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [data-sync-0.1.jar:0.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [data-sync-0.1.jar:0.1]
Caused by: java.io.FileNotFoundException: class path resource [data-sync.yaml] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/huangll/workspace/data-sync/target/data-sync-0.1.jar!/BOOT-INF/classes!/data-sync.yaml
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:180) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at DataPullManager.loadDataSyncConfig(DataPullManager.java:50) ~[classes!/:0.1]
	at DataPullManager.run(DataPullManager.java:44) ~[classes!/:0.1]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	... 13 common frames omitted

2019-05-14 17:36:43.298  INFO 89521 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
